package consulting.deja.cv.variant

import java.nio.charset.StandardCharsets.UTF_8

import consulting.deja.cv.io.IO
import consulting.deja.cv.language.Language
import consulting.deja.cv.language.Language.{English, German}
import consulting.deja.cv.variant.rendering.{StandardOverviewHTML, WebsiteHTML}

import scala.language.postfixOps

/** Denotes a document variant, i.e. a certain design and layout variant of the CV. */
sealed trait Variant {
  /** All languages for which this variant should be applied. */
  def eligibleLanguages:Set[Language]

  /** Produce and build all files this variant represents. */
  def generate[I<:IO[I]](filePrefix:String, language:Language)(io:I):I

  /** Generate all of this variant's files for all eligible languages. */
  def generateForEligibleLanguages[I<:IO[I]](filePrefix:String)(io:I):I =
    eligibleLanguages.foldLeft(io)((i,language) => generate(filePrefix, language)(i))

  /** Name of the variant. */
  def name:String
 }
object Variant {
  val all:Set[Variant] = Set(StandardOverview, Website)

  /** Standard CV format. Gives a mid-level detail overview. Oriented towards printing on paper. */
  object StandardOverview extends Variant {
    override def eligibleLanguages:Set[Language] = Set(English, German)
    override def generate[I<:IO[I]](filePrefix:String, language:Language)(io:I):I = {
      val specificFilePrefix = s"${filePrefix}Matthias-Deja-CV-Overview-${language.isoCode}"
      io.renderPDF(StandardOverviewHTML.root.toCharAppendableFor(language), specificFilePrefix, s"$specificFilePrefix.pdf")
    }
    override def name:String = "standardOverview"
  }

  /** Fragments to be pushed to the website repository. */
  object Website extends Variant {
    override def eligibleLanguages:Set[Language] = Set(German)
    override def generate[I<:IO[I]](filePrefix:String, language:Language)(io:I):I = {
      val specificFilePrefix = s"${filePrefix}website/layouts/shortcodes/autogenerated"
      WebsiteHTML.all.foldLeft(io)((i,fragment) =>
        i.write(fragment._2, s"$specificFilePrefix/${fragment._1}.html", language, UTF_8)
      )
    }
    override def name:String = "website"
  }
}
